title: Akshay's Blog
owner: Akshay Deshmukh
email:
description: Musings on anything and everything
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://akshayd.in" 
language: en
twitter_username:
github_username:
disqus_username: akshayd
# Build settings
markdown: kramdown
theme: minima
future: true

permalink: /:year/:month/:day/:title/

gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/bundle
excerpt_separator: <!--more-->
